numpy advance

In [3]:
# List speed
a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]

c = []
import time

start = time.time()
for i in range(len(a)):
    c.append(a[i] + b[i])
print(time.time()-start)    

3.5401692390441895


In [4]:
# numpy speed
import numpy as np
a = np.arange(10000000)
b = np.arange(10000000,20000000)

start = time.time()
c = a + b
print(time.time()-start)  
    

0.17925572395324707


In [9]:
a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [8]:
# fancy indexing
a[[0,2,3,5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [10]:
a[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [12]:
# Boolean indexing
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[ 7, 16, 15, 27],
       [81, 85, 58, 68],
       [ 8, 17, 27, 83],
       [52,  1, 18, 71],
       [91, 78, 61, 78],
       [ 5, 78, 66,  3]], dtype=int32)

In [14]:
# find all numbers grater than 50

a[a > 50]

array([81, 85, 58, 68, 83, 52, 71, 91, 78, 61, 78, 78, 66], dtype=int32)

In [15]:
# find all numbers grater than 50 and are even
a[(a > 50) & (a % 2 == 0)]

array([58, 68, 52, 78, 78, 78, 66], dtype=int32)

In [17]:
# Broadcasting

a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)

print(a)
print(b)

print(a+b)

[[0 1 2]]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [18]:
a = np.arange(3).reshape(1,3)
b = np.arange(4).reshape(4,1)

print(a)
print(b)

print(a + b)

[[0 1 2]]
[[0]
 [1]
 [2]
 [3]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [19]:
a = np.array([1])
# shape -> (1,1)
b = np.arange(4).reshape(2,2)
# shape -> (2,2)

print(a)
print(b)

print(a + b)

[1]
[[0 1]
 [2 3]]
[[1 2]
 [3 4]]
