#NumPy

In [2]:
import numpy as np

a = np.array([1,2,3])
print(a)


[1 2 3]


In [4]:
#2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

c = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(c)

[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [15]:
#arange
np.arange(1,11)



array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
#with reshape
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [27]:
#ones , zeros and random

np.ones((1,2,3))
np.zeros((4,5,6))
np.random.random((1,2))

array([[0.06622585, 0.18771293]])

In [29]:
# np.linsapce()
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [30]:
#np.identity
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
#Array attributes

a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [34]:
#ndim
a2.ndim

2

In [40]:
#shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [43]:
#size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [44]:
a3.itemsize

8

In [48]:
#changing datatype

a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [49]:
#Array operatins

a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [53]:
# Scalar operations
print(a1)
a1*2

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [55]:
# relational
a2 > 15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [56]:
# vector operations
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

In [58]:
#Array Function
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[ 1., 94.,  8.],
       [15., 22., 21.],
       [37., 16., 22.]])

In [65]:
# max/min/sum/prod
#np.min(a1)
np.max(a1,axis=0)
#np.prod(a2)

array([37., 94., 22.])

In [66]:
#mean/median/std/var
np.var(a1,axis=1)

array([1788.22222222,    9.55555556,   78.        ])

In [69]:
#dot product

a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [73]:
#log and exponents
np.exp(a1)

array([[2.71828183e+00, 6.66317622e+40, 2.98095799e+03],
       [3.26901737e+06, 3.58491285e+09, 1.31881573e+09],
       [1.17191424e+16, 8.88611052e+06, 3.58491285e+09]])

In [75]:
#round/floor/ceil

np.ceil(np.random.random((2,3))*100)


array([[15., 62., 36.],
       [86., 93., 76.]])