In [2]:
#code
import numpy as np
a = np.random.randint(1,100,15)
a

array([87, 12, 11, 19, 81, 87, 47, 80, 56,  9, 67, 25, 10, 89,  6],
      dtype=int32)

In [4]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[35, 53, 76, 66],
       [27, 30, 98, 23],
       [26, 35, 39, 71],
       [56, 36, 16, 80],
       [99, 10, 20, 32],
       [72, 21,  3, 33]], dtype=int32)

In [9]:
np.sort(a)

array([ 6,  9, 10, 11, 12, 19, 25, 47, 56, 67, 80, 81, 87, 87, 89],
      dtype=int32)

In [12]:
np.sort(b,axis = 0)

array([[26, 10,  3, 23],
       [27, 21, 16, 32],
       [35, 30, 20, 33],
       [56, 35, 39, 66],
       [72, 36, 76, 71],
       [99, 53, 98, 80]], dtype=int32)

In [13]:
np.append(a,200)

array([  6,   9,  10,  11,  12,  19,  25,  47,  56,  67,  80,  81,  87,
        87,  89, 200])

In [14]:
b

array([[35, 53, 76, 66],
       [27, 30, 98, 23],
       [26, 35, 39, 71],
       [56, 36, 16, 80],
       [99, 10, 20, 32],
       [72, 21,  3, 33]], dtype=int32)

In [15]:
np.append(b,np.ones((b.shape[0],1)),axis = 1)

array([[35., 53., 76., 66.,  1.],
       [27., 30., 98., 23.,  1.],
       [26., 35., 39., 71.,  1.],
       [56., 36., 16., 80.,  1.],
       [99., 10., 20., 32.,  1.],
       [72., 21.,  3., 33.,  1.]])

In [16]:
#np.concatenate

c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [18]:
np.concatenate((c,d),axis = 0 )


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [20]:
#np.expand_dims
np.expand_dims(a,axis = 1)

array([[ 6],
       [ 9],
       [10],
       [11],
       [12],
       [19],
       [25],
       [47],
       [56],
       [67],
       [80],
       [81],
       [87],
       [87],
       [89]], dtype=int32)

In [30]:
# access index pos which is grater than 50
np.where(b > 50)

(array([0, 0, 0, 1, 2, 3, 3, 4, 5]), array([1, 2, 3, 2, 3, 0, 3, 0, 0]))

In [33]:
# np.argmax
import numpy as np
a = np.random.randint(1,100,15)

np.argmax(a)

np.int64(4)

In [35]:
np.argmax(b,axis = 0)

array([4, 0, 1, 3])

In [36]:
np.cumsum(a)

array([  9,  56, 108, 161, 242, 263, 343, 358, 418, 482, 540, 581, 646,
       705, 766])

In [37]:
a

array([ 9, 47, 52, 53, 81, 21, 80, 15, 60, 64, 58, 41, 65, 59, 61],
      dtype=int32)

In [38]:
np.cumsum(b,axis = 0)

array([[ 35,  53,  76,  66],
       [ 62,  83, 174,  89],
       [ 88, 118, 213, 160],
       [144, 154, 229, 240],
       [243, 164, 249, 272],
       [315, 185, 252, 305]])

In [40]:
np.percentile(a,100)

np.float64(81.0)

In [41]:
np.histogram(a,[0,50,100])

(array([ 5, 10]), array([  0,  50, 100]))

In [44]:
#np.corrcoef

salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])