In [5]:
# Indexing and  Slicing
import numpy as np
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [8]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
a1[0]

np.int64(0)

In [10]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
a2[1,0]

np.int64(4)

In [14]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [15]:
a3[1,0,1]

np.int64(5)

In [17]:
a3[0,0,0]

np.int64(0)

In [18]:
a1[2:5:2]

array([2, 4])

In [19]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
a2[ :,3]

array([ 3,  7, 11])

In [22]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [23]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [24]:
a3 = np.arange(27).reshape(3,3,3)

In [25]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [29]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [30]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [32]:
#iteration

for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [34]:
for i in np.nditer(a1):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [39]:
#horizontal splitting

a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)



In [40]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
np.vstack((a4,a5))